spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

  thymeleaf:
    cache: false

logging:
  level:
    root: info
    com.jamhuang: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080
